package com.cibr.logincenter.dao.user;

import com.cibr.logincenter.entity.CibrUserNotice;
import com.cibr.logincenter.entity.CibrUserNoticeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrUserNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int countByExample(CibrUserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int deleteByExample(CibrUserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int insert(CibrUserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int insertSelective(CibrUserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    List<CibrUserNotice> selectByExample(CibrUserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    CibrUserNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrUserNotice record, @Param("example") CibrUserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrUserNotice record, @Param("example") CibrUserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrUserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_user_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrUserNotice record);
}