package com.cibr.logincenter.dao.user;

import com.cibr.logincenter.entity.CibrSysEmail;
import com.cibr.logincenter.entity.CibrSysEmailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrSysEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int countByExample(CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int insert(CibrSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    List<CibrSysEmail> selectByExampleWithBLOBs(CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    List<CibrSysEmail> selectByExample(CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    CibrSysEmail selectByPrimaryKey(String emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysEmail record, @Param("example") CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CibrSysEmail record, @Param("example") CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysEmail record, @Param("example") CibrSysEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CibrSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysEmail record);
}