package com.cibr.logincenter.dao.user;

import com.cibr.logincenter.entity.CibrSysUserRole;
import com.cibr.logincenter.entity.CibrSysUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CibrSysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int countByExample(CibrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userid") String userid, @Param("roleid") String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int insert(CibrSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    List<CibrSysUserRole> selectByExample(CibrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysUserRole record, @Param("example") CibrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysUserRole record, @Param("example") CibrSysUserRoleExample example);
}