package com.cibr.logincenter.entity;

import java.util.Date;

public class CibrSysWebsite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.englishName
     *
     * @mbggenerated
     */
    private String englishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.descriptions
     *
     * @mbggenerated
     */
    private String descriptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.englishDesc
     *
     * @mbggenerated
     */
    private String englishdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.imgUrl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.curstatu
     *
     * @mbggenerated
     */
    private String curstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_website.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.id
     *
     * @return the value of cibr_sys_website.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.id
     *
     * @param id the value for cibr_sys_website.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.name
     *
     * @return the value of cibr_sys_website.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.name
     *
     * @param name the value for cibr_sys_website.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.englishName
     *
     * @return the value of cibr_sys_website.englishName
     *
     * @mbggenerated
     */
    public String getEnglishname() {
        return englishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.englishName
     *
     * @param englishname the value for cibr_sys_website.englishName
     *
     * @mbggenerated
     */
    public void setEnglishname(String englishname) {
        this.englishname = englishname == null ? null : englishname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.url
     *
     * @return the value of cibr_sys_website.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.url
     *
     * @param url the value for cibr_sys_website.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.descriptions
     *
     * @return the value of cibr_sys_website.descriptions
     *
     * @mbggenerated
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.descriptions
     *
     * @param descriptions the value for cibr_sys_website.descriptions
     *
     * @mbggenerated
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions == null ? null : descriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.englishDesc
     *
     * @return the value of cibr_sys_website.englishDesc
     *
     * @mbggenerated
     */
    public String getEnglishdesc() {
        return englishdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.englishDesc
     *
     * @param englishdesc the value for cibr_sys_website.englishDesc
     *
     * @mbggenerated
     */
    public void setEnglishdesc(String englishdesc) {
        this.englishdesc = englishdesc == null ? null : englishdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.imgUrl
     *
     * @return the value of cibr_sys_website.imgUrl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.imgUrl
     *
     * @param imgurl the value for cibr_sys_website.imgUrl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.curstatu
     *
     * @return the value of cibr_sys_website.curstatu
     *
     * @mbggenerated
     */
    public String getCurstatu() {
        return curstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.curstatu
     *
     * @param curstatu the value for cibr_sys_website.curstatu
     *
     * @mbggenerated
     */
    public void setCurstatu(String curstatu) {
        this.curstatu = curstatu == null ? null : curstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.createTime
     *
     * @return the value of cibr_sys_website.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.createTime
     *
     * @param createtime the value for cibr_sys_website.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_website.creater
     *
     * @return the value of cibr_sys_website.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_website.creater
     *
     * @param creater the value for cibr_sys_website.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }
}