package com.cibr.logincenter.entity;

public class CibrSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_role.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_role.roleid
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_role.userid
     *
     * @return the value of cibr_sys_user_role.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_role.userid
     *
     * @param userid the value for cibr_sys_user_role.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_role.roleid
     *
     * @return the value of cibr_sys_user_role.roleid
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_role.roleid
     *
     * @param roleid the value for cibr_sys_user_role.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }
}