package com.cibr.logincenter.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrSysEmailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public CibrSysEmailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmailIdIsNull() {
            addCriterion("email_id is null");
            return (Criteria) this;
        }

        public Criteria andEmailIdIsNotNull() {
            addCriterion("email_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmailIdEqualTo(String value) {
            addCriterion("email_id =", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotEqualTo(String value) {
            addCriterion("email_id <>", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdGreaterThan(String value) {
            addCriterion("email_id >", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdGreaterThanOrEqualTo(String value) {
            addCriterion("email_id >=", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdLessThan(String value) {
            addCriterion("email_id <", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdLessThanOrEqualTo(String value) {
            addCriterion("email_id <=", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdLike(String value) {
            addCriterion("email_id like", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotLike(String value) {
            addCriterion("email_id not like", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdIn(List<String> values) {
            addCriterion("email_id in", values, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotIn(List<String> values) {
            addCriterion("email_id not in", values, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdBetween(String value1, String value2) {
            addCriterion("email_id between", value1, value2, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotBetween(String value1, String value2) {
            addCriterion("email_id not between", value1, value2, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailFromIsNull() {
            addCriterion("email_from is null");
            return (Criteria) this;
        }

        public Criteria andEmailFromIsNotNull() {
            addCriterion("email_from is not null");
            return (Criteria) this;
        }

        public Criteria andEmailFromEqualTo(String value) {
            addCriterion("email_from =", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotEqualTo(String value) {
            addCriterion("email_from <>", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromGreaterThan(String value) {
            addCriterion("email_from >", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromGreaterThanOrEqualTo(String value) {
            addCriterion("email_from >=", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLessThan(String value) {
            addCriterion("email_from <", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLessThanOrEqualTo(String value) {
            addCriterion("email_from <=", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLike(String value) {
            addCriterion("email_from like", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotLike(String value) {
            addCriterion("email_from not like", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromIn(List<String> values) {
            addCriterion("email_from in", values, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotIn(List<String> values) {
            addCriterion("email_from not in", values, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromBetween(String value1, String value2) {
            addCriterion("email_from between", value1, value2, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotBetween(String value1, String value2) {
            addCriterion("email_from not between", value1, value2, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNull() {
            addCriterion("email_to is null");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNotNull() {
            addCriterion("email_to is not null");
            return (Criteria) this;
        }

        public Criteria andEmailToEqualTo(String value) {
            addCriterion("email_to =", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotEqualTo(String value) {
            addCriterion("email_to <>", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThan(String value) {
            addCriterion("email_to >", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThanOrEqualTo(String value) {
            addCriterion("email_to >=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThan(String value) {
            addCriterion("email_to <", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThanOrEqualTo(String value) {
            addCriterion("email_to <=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLike(String value) {
            addCriterion("email_to like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotLike(String value) {
            addCriterion("email_to not like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToIn(List<String> values) {
            addCriterion("email_to in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotIn(List<String> values) {
            addCriterion("email_to not in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToBetween(String value1, String value2) {
            addCriterion("email_to between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotBetween(String value1, String value2) {
            addCriterion("email_to not between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectIsNull() {
            addCriterion("email_subject is null");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectIsNotNull() {
            addCriterion("email_subject is not null");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectEqualTo(String value) {
            addCriterion("email_subject =", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectNotEqualTo(String value) {
            addCriterion("email_subject <>", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectGreaterThan(String value) {
            addCriterion("email_subject >", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("email_subject >=", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectLessThan(String value) {
            addCriterion("email_subject <", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectLessThanOrEqualTo(String value) {
            addCriterion("email_subject <=", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectLike(String value) {
            addCriterion("email_subject like", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectNotLike(String value) {
            addCriterion("email_subject not like", value, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectIn(List<String> values) {
            addCriterion("email_subject in", values, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectNotIn(List<String> values) {
            addCriterion("email_subject not in", values, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectBetween(String value1, String value2) {
            addCriterion("email_subject between", value1, value2, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSubjectNotBetween(String value1, String value2) {
            addCriterion("email_subject not between", value1, value2, "emailSubject");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateIsNull() {
            addCriterion("email_sentDate is null");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateIsNotNull() {
            addCriterion("email_sentDate is not null");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateEqualTo(Date value) {
            addCriterion("email_sentDate =", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateNotEqualTo(Date value) {
            addCriterion("email_sentDate <>", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateGreaterThan(Date value) {
            addCriterion("email_sentDate >", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateGreaterThanOrEqualTo(Date value) {
            addCriterion("email_sentDate >=", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateLessThan(Date value) {
            addCriterion("email_sentDate <", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateLessThanOrEqualTo(Date value) {
            addCriterion("email_sentDate <=", value, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateIn(List<Date> values) {
            addCriterion("email_sentDate in", values, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateNotIn(List<Date> values) {
            addCriterion("email_sentDate not in", values, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateBetween(Date value1, Date value2) {
            addCriterion("email_sentDate between", value1, value2, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailSentdateNotBetween(Date value1, Date value2) {
            addCriterion("email_sentDate not between", value1, value2, "emailSentdate");
            return (Criteria) this;
        }

        public Criteria andEmailCcIsNull() {
            addCriterion("email_cc is null");
            return (Criteria) this;
        }

        public Criteria andEmailCcIsNotNull() {
            addCriterion("email_cc is not null");
            return (Criteria) this;
        }

        public Criteria andEmailCcEqualTo(String value) {
            addCriterion("email_cc =", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcNotEqualTo(String value) {
            addCriterion("email_cc <>", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcGreaterThan(String value) {
            addCriterion("email_cc >", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcGreaterThanOrEqualTo(String value) {
            addCriterion("email_cc >=", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcLessThan(String value) {
            addCriterion("email_cc <", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcLessThanOrEqualTo(String value) {
            addCriterion("email_cc <=", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcLike(String value) {
            addCriterion("email_cc like", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcNotLike(String value) {
            addCriterion("email_cc not like", value, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcIn(List<String> values) {
            addCriterion("email_cc in", values, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcNotIn(List<String> values) {
            addCriterion("email_cc not in", values, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcBetween(String value1, String value2) {
            addCriterion("email_cc between", value1, value2, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailCcNotBetween(String value1, String value2) {
            addCriterion("email_cc not between", value1, value2, "emailCc");
            return (Criteria) this;
        }

        public Criteria andEmailBccIsNull() {
            addCriterion("email_bcc is null");
            return (Criteria) this;
        }

        public Criteria andEmailBccIsNotNull() {
            addCriterion("email_bcc is not null");
            return (Criteria) this;
        }

        public Criteria andEmailBccEqualTo(String value) {
            addCriterion("email_bcc =", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccNotEqualTo(String value) {
            addCriterion("email_bcc <>", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccGreaterThan(String value) {
            addCriterion("email_bcc >", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccGreaterThanOrEqualTo(String value) {
            addCriterion("email_bcc >=", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccLessThan(String value) {
            addCriterion("email_bcc <", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccLessThanOrEqualTo(String value) {
            addCriterion("email_bcc <=", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccLike(String value) {
            addCriterion("email_bcc like", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccNotLike(String value) {
            addCriterion("email_bcc not like", value, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccIn(List<String> values) {
            addCriterion("email_bcc in", values, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccNotIn(List<String> values) {
            addCriterion("email_bcc not in", values, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccBetween(String value1, String value2) {
            addCriterion("email_bcc between", value1, value2, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailBccNotBetween(String value1, String value2) {
            addCriterion("email_bcc not between", value1, value2, "emailBcc");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIsNull() {
            addCriterion("email_status is null");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIsNotNull() {
            addCriterion("email_status is not null");
            return (Criteria) this;
        }

        public Criteria andEmailStatusEqualTo(String value) {
            addCriterion("email_status =", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotEqualTo(String value) {
            addCriterion("email_status <>", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusGreaterThan(String value) {
            addCriterion("email_status >", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusGreaterThanOrEqualTo(String value) {
            addCriterion("email_status >=", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusLessThan(String value) {
            addCriterion("email_status <", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusLessThanOrEqualTo(String value) {
            addCriterion("email_status <=", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusLike(String value) {
            addCriterion("email_status like", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotLike(String value) {
            addCriterion("email_status not like", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIn(List<String> values) {
            addCriterion("email_status in", values, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotIn(List<String> values) {
            addCriterion("email_status not in", values, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusBetween(String value1, String value2) {
            addCriterion("email_status between", value1, value2, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotBetween(String value1, String value2) {
            addCriterion("email_status not between", value1, value2, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailErrorIsNull() {
            addCriterion("email_error is null");
            return (Criteria) this;
        }

        public Criteria andEmailErrorIsNotNull() {
            addCriterion("email_error is not null");
            return (Criteria) this;
        }

        public Criteria andEmailErrorEqualTo(String value) {
            addCriterion("email_error =", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorNotEqualTo(String value) {
            addCriterion("email_error <>", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorGreaterThan(String value) {
            addCriterion("email_error >", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorGreaterThanOrEqualTo(String value) {
            addCriterion("email_error >=", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorLessThan(String value) {
            addCriterion("email_error <", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorLessThanOrEqualTo(String value) {
            addCriterion("email_error <=", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorLike(String value) {
            addCriterion("email_error like", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorNotLike(String value) {
            addCriterion("email_error not like", value, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorIn(List<String> values) {
            addCriterion("email_error in", values, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorNotIn(List<String> values) {
            addCriterion("email_error not in", values, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorBetween(String value1, String value2) {
            addCriterion("email_error between", value1, value2, "emailError");
            return (Criteria) this;
        }

        public Criteria andEmailErrorNotBetween(String value1, String value2) {
            addCriterion("email_error not between", value1, value2, "emailError");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_email
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_email
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}