package com.cibr.logincenter.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.web.multipart.MultipartFile;

import java.util.Date;

public class CibrSysEmail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_id
     *
     * @mbggenerated
     */
    private String emailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_from
     *
     * @mbggenerated
     */
    private String emailFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_to
     *
     * @mbggenerated
     */
    private String emailTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_subject
     *
     * @mbggenerated
     */
    private String emailSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_sentDate
     *
     * @mbggenerated
     */
    private Date emailSentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_cc
     *
     * @mbggenerated
     */
    private String emailCc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_bcc
     *
     * @mbggenerated
     */
    private String emailBcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_status
     *
     * @mbggenerated
     */
    private String emailStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_error
     *
     * @mbggenerated
     */
    private String emailError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_email.email_text
     *
     * @mbggenerated
     */
    private String emailText;

    @JsonIgnore
    private MultipartFile[] multipartFiles;

    public MultipartFile[] getMultipartFiles() {
        return multipartFiles;
    }

    public void setMultipartFiles(MultipartFile[] multipartFiles) {
        this.multipartFiles = multipartFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_id
     *
     * @return the value of cibr_sys_email.email_id
     *
     * @mbggenerated
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_id
     *
     * @param emailId the value for cibr_sys_email.email_id
     *
     * @mbggenerated
     */
    public void setEmailId(String emailId) {
        this.emailId = emailId == null ? null : emailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_from
     *
     * @return the value of cibr_sys_email.email_from
     *
     * @mbggenerated
     */
    public String getEmailFrom() {
        return emailFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_from
     *
     * @param emailFrom the value for cibr_sys_email.email_from
     *
     * @mbggenerated
     */
    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom == null ? null : emailFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_to
     *
     * @return the value of cibr_sys_email.email_to
     *
     * @mbggenerated
     */
    public String getEmailTo() {
        return emailTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_to
     *
     * @param emailTo the value for cibr_sys_email.email_to
     *
     * @mbggenerated
     */
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo == null ? null : emailTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_subject
     *
     * @return the value of cibr_sys_email.email_subject
     *
     * @mbggenerated
     */
    public String getEmailSubject() {
        return emailSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_subject
     *
     * @param emailSubject the value for cibr_sys_email.email_subject
     *
     * @mbggenerated
     */
    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject == null ? null : emailSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_sentDate
     *
     * @return the value of cibr_sys_email.email_sentDate
     *
     * @mbggenerated
     */
    public Date getEmailSentdate() {
        return emailSentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_sentDate
     *
     * @param emailSentdate the value for cibr_sys_email.email_sentDate
     *
     * @mbggenerated
     */
    public void setEmailSentdate(Date emailSentdate) {
        this.emailSentdate = emailSentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_cc
     *
     * @return the value of cibr_sys_email.email_cc
     *
     * @mbggenerated
     */
    public String getEmailCc() {
        return emailCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_cc
     *
     * @param emailCc the value for cibr_sys_email.email_cc
     *
     * @mbggenerated
     */
    public void setEmailCc(String emailCc) {
        this.emailCc = emailCc == null ? null : emailCc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_bcc
     *
     * @return the value of cibr_sys_email.email_bcc
     *
     * @mbggenerated
     */
    public String getEmailBcc() {
        return emailBcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_bcc
     *
     * @param emailBcc the value for cibr_sys_email.email_bcc
     *
     * @mbggenerated
     */
    public void setEmailBcc(String emailBcc) {
        this.emailBcc = emailBcc == null ? null : emailBcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_status
     *
     * @return the value of cibr_sys_email.email_status
     *
     * @mbggenerated
     */
    public String getEmailStatus() {
        return emailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_status
     *
     * @param emailStatus the value for cibr_sys_email.email_status
     *
     * @mbggenerated
     */
    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus == null ? null : emailStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_error
     *
     * @return the value of cibr_sys_email.email_error
     *
     * @mbggenerated
     */
    public String getEmailError() {
        return emailError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_error
     *
     * @param emailError the value for cibr_sys_email.email_error
     *
     * @mbggenerated
     */
    public void setEmailError(String emailError) {
        this.emailError = emailError == null ? null : emailError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_email.email_text
     *
     * @return the value of cibr_sys_email.email_text
     *
     * @mbggenerated
     */
    public String getEmailText() {
        return emailText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_email.email_text
     *
     * @param emailText the value for cibr_sys_email.email_text
     *
     * @mbggenerated
     */
    public void setEmailText(String emailText) {
        this.emailText = emailText == null ? null : emailText.trim();
    }
}