package com.cibr.logincenter.entity;

import java.util.List;

public class CibrSysUserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.groupdesc
     *
     * @mbggenerated
     */
    private String groupdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.groupadmin
     *
     * @mbggenerated
     */
    private String groupadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.groupStatu
     *
     * @mbggenerated
     */
    private String groupstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.grouptype
     *
     * @mbggenerated
     */
    private String grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user_group.groupEnglishName
     *
     * @mbggenerated
     */
    private String groupenglishname;

    private List<CibrSysUser> users;

    private CibrSysUser admin;

    public CibrSysUser getAdmin() {
        return admin;
    }

    public void setAdmin(CibrSysUser admin) {
        this.admin = admin;
    }

    public List<CibrSysUser> getUsers() {
        return users;
    }

    public void setUsers(List<CibrSysUser> users) {
        this.users = users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.id
     *
     * @return the value of cibr_sys_user_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.id
     *
     * @param id the value for cibr_sys_user_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.groupname
     *
     * @return the value of cibr_sys_user_group.groupname
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.groupname
     *
     * @param groupname the value for cibr_sys_user_group.groupname
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.groupdesc
     *
     * @return the value of cibr_sys_user_group.groupdesc
     *
     * @mbggenerated
     */
    public String getGroupdesc() {
        return groupdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.groupdesc
     *
     * @param groupdesc the value for cibr_sys_user_group.groupdesc
     *
     * @mbggenerated
     */
    public void setGroupdesc(String groupdesc) {
        this.groupdesc = groupdesc == null ? null : groupdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.groupadmin
     *
     * @return the value of cibr_sys_user_group.groupadmin
     *
     * @mbggenerated
     */
    public String getGroupadmin() {
        return groupadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.groupadmin
     *
     * @param groupadmin the value for cibr_sys_user_group.groupadmin
     *
     * @mbggenerated
     */
    public void setGroupadmin(String groupadmin) {
        this.groupadmin = groupadmin == null ? null : groupadmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.groupStatu
     *
     * @return the value of cibr_sys_user_group.groupStatu
     *
     * @mbggenerated
     */
    public String getGroupstatu() {
        return groupstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.groupStatu
     *
     * @param groupstatu the value for cibr_sys_user_group.groupStatu
     *
     * @mbggenerated
     */
    public void setGroupstatu(String groupstatu) {
        this.groupstatu = groupstatu == null ? null : groupstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.grouptype
     *
     * @return the value of cibr_sys_user_group.grouptype
     *
     * @mbggenerated
     */
    public String getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.grouptype
     *
     * @param grouptype the value for cibr_sys_user_group.grouptype
     *
     * @mbggenerated
     */
    public void setGrouptype(String grouptype) {
        this.grouptype = grouptype == null ? null : grouptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user_group.groupEnglishName
     *
     * @return the value of cibr_sys_user_group.groupEnglishName
     *
     * @mbggenerated
     */
    public String getGroupenglishname() {
        return groupenglishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user_group.groupEnglishName
     *
     * @param groupenglishname the value for cibr_sys_user_group.groupEnglishName
     *
     * @mbggenerated
     */
    public void setGroupenglishname(String groupenglishname) {
        this.groupenglishname = groupenglishname == null ? null : groupenglishname.trim();
    }
}