package com.cibr.logincenter.entity;

public class CibrUserNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.email
     *
     * @mbggenerated
     */
    private Boolean email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.web
     *
     * @mbggenerated
     */
    private Boolean web;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.phone
     *
     * @mbggenerated
     */
    private Boolean phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_user_notice.wechat
     *
     * @mbggenerated
     */
    private Boolean wechat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.id
     *
     * @return the value of cibr_user_notice.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.id
     *
     * @param id the value for cibr_user_notice.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.userId
     *
     * @return the value of cibr_user_notice.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.userId
     *
     * @param userid the value for cibr_user_notice.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.email
     *
     * @return the value of cibr_user_notice.email
     *
     * @mbggenerated
     */
    public Boolean getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.email
     *
     * @param email the value for cibr_user_notice.email
     *
     * @mbggenerated
     */
    public void setEmail(Boolean email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.web
     *
     * @return the value of cibr_user_notice.web
     *
     * @mbggenerated
     */
    public Boolean getWeb() {
        return web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.web
     *
     * @param web the value for cibr_user_notice.web
     *
     * @mbggenerated
     */
    public void setWeb(Boolean web) {
        this.web = web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.phone
     *
     * @return the value of cibr_user_notice.phone
     *
     * @mbggenerated
     */
    public Boolean getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.phone
     *
     * @param phone the value for cibr_user_notice.phone
     *
     * @mbggenerated
     */
    public void setPhone(Boolean phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_user_notice.wechat
     *
     * @return the value of cibr_user_notice.wechat
     *
     * @mbggenerated
     */
    public Boolean getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_user_notice.wechat
     *
     * @param wechat the value for cibr_user_notice.wechat
     *
     * @mbggenerated
     */
    public void setWechat(Boolean wechat) {
        this.wechat = wechat;
    }
}