package com.cibr.logincenter.entity;

public class CibrSysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_role.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_role.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_role.roleType
     *
     * @mbggenerated
     */
    private String roletype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_role.id
     *
     * @return the value of cibr_sys_role.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_role.id
     *
     * @param id the value for cibr_sys_role.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_role.roleName
     *
     * @return the value of cibr_sys_role.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_role.roleName
     *
     * @param rolename the value for cibr_sys_role.roleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_role.roleType
     *
     * @return the value of cibr_sys_role.roleType
     *
     * @mbggenerated
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_role.roleType
     *
     * @param roletype the value for cibr_sys_role.roleType
     *
     * @mbggenerated
     */
    public void setRoletype(String roletype) {
        this.roletype = roletype == null ? null : roletype.trim();
    }
}