package com.cibr.logincenter.entity;

import java.util.Date;
import java.util.List;

public class CibrSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.englishName
     *
     * @mbggenerated
     */
    private String englishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.groupid
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.userhead
     *
     * @mbggenerated
     */
    private String userhead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.userstatu
     *
     * @mbggenerated
     */
    private String userstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    private String validate;

    List<CibrSysRole> roles;

    private CibrSysUserGroup group;

    private List<String> roleIds;

    public List<String> getRoleIds() {
        return roleIds;
    }

    public void setRoleIds(List<String> roleIds) {
        this.roleIds = roleIds;
    }

    public CibrSysUserGroup getGroup() {
        return group;
    }

    public void setGroup(CibrSysUserGroup group) {
        this.group = group;
    }

    public List<CibrSysRole> getRoles() {
        return roles;
    }

    public void setRoles(List<CibrSysRole> roles) {
        this.roles = roles;
    }

    public String getValidate() {
        return validate;
    }

    public void setValidate(String validate) {
        this.validate = validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.id
     *
     * @return the value of cibr_sys_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.id
     *
     * @param id the value for cibr_sys_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.englishName
     *
     * @return the value of cibr_sys_user.englishName
     *
     * @mbggenerated
     */
    public String getEnglishname() {
        return englishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.englishName
     *
     * @param englishname the value for cibr_sys_user.englishName
     *
     * @mbggenerated
     */
    public void setEnglishname(String englishname) {
        this.englishname = englishname == null ? null : englishname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.name
     *
     * @return the value of cibr_sys_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.name
     *
     * @param name the value for cibr_sys_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.password
     *
     * @return the value of cibr_sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.password
     *
     * @param password the value for cibr_sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.email
     *
     * @return the value of cibr_sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.email
     *
     * @param email the value for cibr_sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.groupid
     *
     * @return the value of cibr_sys_user.groupid
     *
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.groupid
     *
     * @param groupid the value for cibr_sys_user.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.userhead
     *
     * @return the value of cibr_sys_user.userhead
     *
     * @mbggenerated
     */
    public String getUserhead() {
        return userhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.userhead
     *
     * @param userhead the value for cibr_sys_user.userhead
     *
     * @mbggenerated
     */
    public void setUserhead(String userhead) {
        this.userhead = userhead == null ? null : userhead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.userstatu
     *
     * @return the value of cibr_sys_user.userstatu
     *
     * @mbggenerated
     */
    public String getUserstatu() {
        return userstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.userstatu
     *
     * @param userstatu the value for cibr_sys_user.userstatu
     *
     * @mbggenerated
     */
    public void setUserstatu(String userstatu) {
        this.userstatu = userstatu == null ? null : userstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.createtime
     *
     * @return the value of cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.createtime
     *
     * @param createtime the value for cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}