package com.cibr.logincenter.entity;

import java.util.ArrayList;
import java.util.List;

public class CibrSysUserGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public CibrSysUserGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNull() {
            addCriterion("groupname is null");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNotNull() {
            addCriterion("groupname is not null");
            return (Criteria) this;
        }

        public Criteria andGroupnameEqualTo(String value) {
            addCriterion("groupname =", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotEqualTo(String value) {
            addCriterion("groupname <>", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThan(String value) {
            addCriterion("groupname >", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThanOrEqualTo(String value) {
            addCriterion("groupname >=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThan(String value) {
            addCriterion("groupname <", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThanOrEqualTo(String value) {
            addCriterion("groupname <=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLike(String value) {
            addCriterion("groupname like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotLike(String value) {
            addCriterion("groupname not like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameIn(List<String> values) {
            addCriterion("groupname in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotIn(List<String> values) {
            addCriterion("groupname not in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameBetween(String value1, String value2) {
            addCriterion("groupname between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotBetween(String value1, String value2) {
            addCriterion("groupname not between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupdescIsNull() {
            addCriterion("groupdesc is null");
            return (Criteria) this;
        }

        public Criteria andGroupdescIsNotNull() {
            addCriterion("groupdesc is not null");
            return (Criteria) this;
        }

        public Criteria andGroupdescEqualTo(String value) {
            addCriterion("groupdesc =", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescNotEqualTo(String value) {
            addCriterion("groupdesc <>", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescGreaterThan(String value) {
            addCriterion("groupdesc >", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescGreaterThanOrEqualTo(String value) {
            addCriterion("groupdesc >=", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescLessThan(String value) {
            addCriterion("groupdesc <", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescLessThanOrEqualTo(String value) {
            addCriterion("groupdesc <=", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescLike(String value) {
            addCriterion("groupdesc like", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescNotLike(String value) {
            addCriterion("groupdesc not like", value, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescIn(List<String> values) {
            addCriterion("groupdesc in", values, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescNotIn(List<String> values) {
            addCriterion("groupdesc not in", values, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescBetween(String value1, String value2) {
            addCriterion("groupdesc between", value1, value2, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupdescNotBetween(String value1, String value2) {
            addCriterion("groupdesc not between", value1, value2, "groupdesc");
            return (Criteria) this;
        }

        public Criteria andGroupadminIsNull() {
            addCriterion("groupadmin is null");
            return (Criteria) this;
        }

        public Criteria andGroupadminIsNotNull() {
            addCriterion("groupadmin is not null");
            return (Criteria) this;
        }

        public Criteria andGroupadminEqualTo(String value) {
            addCriterion("groupadmin =", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminNotEqualTo(String value) {
            addCriterion("groupadmin <>", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminGreaterThan(String value) {
            addCriterion("groupadmin >", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminGreaterThanOrEqualTo(String value) {
            addCriterion("groupadmin >=", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminLessThan(String value) {
            addCriterion("groupadmin <", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminLessThanOrEqualTo(String value) {
            addCriterion("groupadmin <=", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminLike(String value) {
            addCriterion("groupadmin like", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminNotLike(String value) {
            addCriterion("groupadmin not like", value, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminIn(List<String> values) {
            addCriterion("groupadmin in", values, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminNotIn(List<String> values) {
            addCriterion("groupadmin not in", values, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminBetween(String value1, String value2) {
            addCriterion("groupadmin between", value1, value2, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupadminNotBetween(String value1, String value2) {
            addCriterion("groupadmin not between", value1, value2, "groupadmin");
            return (Criteria) this;
        }

        public Criteria andGroupstatuIsNull() {
            addCriterion("groupStatu is null");
            return (Criteria) this;
        }

        public Criteria andGroupstatuIsNotNull() {
            addCriterion("groupStatu is not null");
            return (Criteria) this;
        }

        public Criteria andGroupstatuEqualTo(String value) {
            addCriterion("groupStatu =", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuNotEqualTo(String value) {
            addCriterion("groupStatu <>", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuGreaterThan(String value) {
            addCriterion("groupStatu >", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuGreaterThanOrEqualTo(String value) {
            addCriterion("groupStatu >=", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuLessThan(String value) {
            addCriterion("groupStatu <", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuLessThanOrEqualTo(String value) {
            addCriterion("groupStatu <=", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuLike(String value) {
            addCriterion("groupStatu like", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuNotLike(String value) {
            addCriterion("groupStatu not like", value, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuIn(List<String> values) {
            addCriterion("groupStatu in", values, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuNotIn(List<String> values) {
            addCriterion("groupStatu not in", values, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuBetween(String value1, String value2) {
            addCriterion("groupStatu between", value1, value2, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGroupstatuNotBetween(String value1, String value2) {
            addCriterion("groupStatu not between", value1, value2, "groupstatu");
            return (Criteria) this;
        }

        public Criteria andGrouptypeIsNull() {
            addCriterion("grouptype is null");
            return (Criteria) this;
        }

        public Criteria andGrouptypeIsNotNull() {
            addCriterion("grouptype is not null");
            return (Criteria) this;
        }

        public Criteria andGrouptypeEqualTo(String value) {
            addCriterion("grouptype =", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeNotEqualTo(String value) {
            addCriterion("grouptype <>", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeGreaterThan(String value) {
            addCriterion("grouptype >", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeGreaterThanOrEqualTo(String value) {
            addCriterion("grouptype >=", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeLessThan(String value) {
            addCriterion("grouptype <", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeLessThanOrEqualTo(String value) {
            addCriterion("grouptype <=", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeLike(String value) {
            addCriterion("grouptype like", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeNotLike(String value) {
            addCriterion("grouptype not like", value, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeIn(List<String> values) {
            addCriterion("grouptype in", values, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeNotIn(List<String> values) {
            addCriterion("grouptype not in", values, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeBetween(String value1, String value2) {
            addCriterion("grouptype between", value1, value2, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGrouptypeNotBetween(String value1, String value2) {
            addCriterion("grouptype not between", value1, value2, "grouptype");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameIsNull() {
            addCriterion("groupEnglishName is null");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameIsNotNull() {
            addCriterion("groupEnglishName is not null");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameEqualTo(String value) {
            addCriterion("groupEnglishName =", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameNotEqualTo(String value) {
            addCriterion("groupEnglishName <>", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameGreaterThan(String value) {
            addCriterion("groupEnglishName >", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("groupEnglishName >=", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameLessThan(String value) {
            addCriterion("groupEnglishName <", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameLessThanOrEqualTo(String value) {
            addCriterion("groupEnglishName <=", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameLike(String value) {
            addCriterion("groupEnglishName like", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameNotLike(String value) {
            addCriterion("groupEnglishName not like", value, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameIn(List<String> values) {
            addCriterion("groupEnglishName in", values, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameNotIn(List<String> values) {
            addCriterion("groupEnglishName not in", values, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameBetween(String value1, String value2) {
            addCriterion("groupEnglishName between", value1, value2, "groupenglishname");
            return (Criteria) this;
        }

        public Criteria andGroupenglishnameNotBetween(String value1, String value2) {
            addCriterion("groupEnglishName not between", value1, value2, "groupenglishname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}